version: 1.0.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

cache:
  - src\packages -> **\packages.config

platform: Any CPU

configuration: Release

before_build:
  - nuget restore src\Gerrit.Api.sln
  
build:
  project: src\Gerrit.Api.sln
  publish_nuget: true
  
deploy:
  provider: NuGet
  api_key:
    secure: 5fkjdFMJQ6JeFcST9Jqgv5Du09z8/ayuIE6lb6ExDMSQ0SqdJKRsC5xxRo8nrHpS
  artifact: /.*\.nupkg/

artifacts:
  - path: '\src\Gerrit.Api*\**\*.nupkg'