version: 1.0.{build}

cache:
  - src\packages -> **\packages.config

platform: Any CPU

configuration: Release

before_build:
  - nuget restore src\Gerrit.Api.sln
  
build:
  
after_build:
  - nuget pack src\Gerrit.Api.Domain\Gerrit.Api.Domain.nuspec -Version %appveyor_build_version%
  - nuget pack src\Gerrit.Api\Gerrit.Api.nuspec -Version %appveyor_build_version%
  
  
deploy:
  provider: NuGet
  api_key:
    secure: 2195ba75-c692-436e-af9d-5e5af9b01f25
  artifact: \src\Gerrit.Api*\**\*.nupkg

artifacts:
  - path: '\src\Gerrit.Api*\**\*.nupkg'